convert to matrix job; hacks for less modern distros

diff --git a/.github/workflows/main-latest.yml b/.github/workflows/main-latest.yml
--- a/.github/workflows/main-latest.yml
+++ b/.github/workflows/main-latest.yml
@@ -5,8 +5,26 @@ on:
     branches: [ main ]
 
 jobs:
-  docker:
+
+  prepare:
     runs-on: ubuntu-latest
+    steps:
+      - name: Prepare release ID
+        id: prep
+        run: |
+          echo ::set-output name=created::$(date -u +'%Y%m%d-%H%M')
+    outputs:
+      created: ${{ steps.prep.outputs.created }} # refer to as ${{needs.prepare.outputs.created}}
+
+
+  build:
+    needs: [ prepare ]
+    runs-on: ubuntu-latest # soon to support hosted runners for arm64
+    strategy:
+      fail-fast: false # let other jobs try to complete if one fails
+      matrix:
+        arch: [ 'amd64' ]
+        distro: [ 'ubuntu:hirsute', 'golang:1.16-bullseye' ]
     steps:
 
       - name: Checkout
@@ -19,108 +37,99 @@ jobs:
         id: buildx
         uses: docker/setup-buildx-action@v1
 
-      - name: Cache Docker layers amd64
+      - name: Cache Docker layers ${{ matrix.arch }} ${{ matrix.distro }}
         uses: actions/cache@v2
         with:
-          path: /tmp/.buildx-cache-amd64
-          key: ${{ runner.os }}-buildx-amd64-${{ github.sha }}
+          path: /tmp/.buildx-cache
+          key: ${{ runner.os }}-buildx-${{ matrix.arch }}-${{ matrix.distro }}-${{ github.sha }}
           restore-keys: |
-            ${{ runner.os }}-buildx-amd64
+            ${{ runner.os }}-buildx-${{ matrix.arch }}-${{ matrix.distro }}
 
-      - name: Prepare
-        id: prep
+      - name: Build ${{ matrix.arch }} ${{ matrix.distro }}
+        uses: docker/build-push-action@v2
+        with:
+          context: .
+          file: ./Dockerfile
+          platforms: linux/${{ matrix.arch }}
+          load: true
+          push: false
+          tags: k8s-worker-containerd:${{ matrix.arch }}
+          cache-from: type=local,src=/tmp/.buildx-cache
+          cache-to: type=local,dest=/tmp/.buildx-cache-new #,mode=max
+          build-args: |
+            PACKAGE_VERSION=${{needs.prepare.outputs.created}}
+            BASE_IMAGE=${{ matrix.distro }}
+            OS_ARCH=${{ matrix.arch }}
+
+      - name: Extract artifacts from docker ${{ matrix.arch }} ${{ matrix.distro }}
+        run: docker cp $(docker create --rm k8s-worker-containerd:${{ matrix.arch }}):/out ./
+
+      - name: Upload deb as artifact ${{ matrix.arch }} ${{ matrix.distro }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: deb
+          path: out/*.deb
+
+      - name: Upload tarball as artifact ${{ matrix.arch }} ${{ matrix.distro }}
+        uses: actions/upload-artifact@v2
+        with:
+          name: tarball
+          path: out/*.tar.gz
+
+      # Temp fix: https://github.com/docker/build-push-action/issues/252
+      - name: Move caches ${{ matrix.arch }} ${{ matrix.distro }}
         run: |
-          echo ::set-output name=created::$(date -u +'%Y%m%d-%H%M')
+          echo "Old ${{ matrix.arch }} ${{ matrix.distro }} cache..."
+          ls -lahtR /tmp/.buildx-cache || true
+          if [[ -d /tmp/.buildx-cache-new ]]; then
+            echo "New  ${{ matrix.arch }} ${{ matrix.distro }} cache..."
+            ls -lahtR /tmp/.buildx-cache-new
+            echo "Flipping  ${{ matrix.arch }} ${{ matrix.distro }} cache..."
+            rm -rf /tmp/.buildx-cache
+            mv /tmp/.buildx-cache-new /tmp/.buildx-cache
+          fi
 
-      - name: Build amd64
-        id: docker_build_amd64
-        uses: docker/build-push-action@v2
+  release:
+    needs: [ prepare, build ]
+    runs-on: ubuntu-latest
+    steps:
+      # Download the built artifacts from GH artifacts.  
+      - uses: actions/download-artifact@v2
+        name: Download deb artifacts
         with:
-          context: .
-          file: ./Dockerfile
-          platforms: linux/amd64
-          load: true
-          push: false
-          tags: k8s-worker-containerd:amd64
-          cache-from: type=local,src=/tmp/.buildx-cache-amd64
-          cache-to: type=local,dest=/tmp/.buildx-cache-amd64-new,mode=max
-          build-args: |
-            PACKAGE_VERSION=${{ steps.prep.outputs.created }}
-            OS_ARCH=amd64
+          name: deb
+          path: out
 
-      - name: Extract artifacts from amd64 docker build
-        run: docker cp $(docker create --rm k8s-worker-containerd:amd64):/out ./
-
-      - name: Cache Docker layers arm64
-        if: "${{ false }}" # disabled
-        uses: actions/cache@v2
+      - uses: actions/download-artifact@v2
+        name: Download tarball artifacts
         with:
-          path: /tmp/.buildx-cache-arm64
-          key: ${{ runner.os }}-buildx-arm64-${{ github.sha }}
-          restore-keys: |
-            ${{ runner.os }}-buildx-arm64
+          name: tarball
+          path: out
 
-      - name: Build arm64
-        if: "${{ false }}" # disabled
-        id: docker_build_arm64
-        uses: docker/build-push-action@v2
-        with:
-          context: .
-          file: ./Dockerfile
-          platforms: linux/arm64
-          load: true
-          push: false
-          tags: k8s-worker-containerd:arm64
-          cache-from: type=local,src=/tmp/.buildx-cache-arm64
-          cache-to: type=local,dest=/tmp/.buildx-cache-arm64-new,mode=max
-          build-args: |
-            PACKAGE_VERSION=${{ steps.prep.outputs.created }}
-            OS_ARCH=arm64
+      - name: List artifacts downloaded
+        run: |
+          ls -lahtR
 
-      - name: Extract artifacts from arm64 docker build
-        if: "${{ false }}" # disabled
-        run: docker cp $(docker create --rm k8s-worker-containerd:arm64):/out ./
-
+      # Release the artifacts into GitHub Releases
       - name: "GH specific release"
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
           repo_token: "${{ secrets.GITHUB_TOKEN }}"
-          automatic_release_tag: "${{ steps.prep.outputs.created }}"
+          automatic_release_tag: "${{needs.prepare.outputs.created}}"
           prerelease: false
-          title: "${{ steps.prep.outputs.created }}"
+          title: "${{needs.prepare.outputs.created}}"
           files: |
             out/*.deb
             out/*.tar.gz
 
-      - name: "GH latest release"
-        uses: "marvinpinto/action-automatic-releases@latest"
-        with:
-          repo_token: "${{ secrets.GITHUB_TOKEN }}"
-          automatic_release_tag: "latest"
-          prerelease: false
-          title: "Latest: ${{ steps.prep.outputs.created }}"
-          files: |
-            out/*.deb
-            out/*.tar.gz
+      #- name: "GH latest release"
+      #  uses: "marvinpinto/action-automatic-releases@latest"
+      #  with:
+      #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
+      #    automatic_release_tag: "latest"
+      #    prerelease: false
+      #    title: "Latest: ${{needs.prepare.outputs.created}}"
+      #    files: |
+      #      out/*.deb
+      #      out/*.tar.gz
 
-      # Temp fix: https://github.com/docker/build-push-action/issues/252
-      - name: Move caches
-        run: |
-          echo "Old amd64 cache..."
-          ls -lahtR /tmp/.buildx-cache-amd64 || true
-          if [[ -d /tmp/.buildx-cache-amd64-new ]]; then
-            echo "New amd64 cache..."
-            ls -lahtR /tmp/.buildx-cache-amd64-new
-            echo "Flipping amd64 cache..."
-            rm -rf /tmp/.buildx-cache-amd64
-            mv /tmp/.buildx-cache-amd64-new /tmp/.buildx-cache-amd64
-          fi
-          echo "Old arm64 cache..."
-          ls -lahtR /tmp/.buildx-cache-arm64 || true
-          if [[ -d /tmp/.buildx-cache-arm64-new ]]; then
-            echo "New arm64 cache..."
-            ls -lahtR /tmp/.buildx-cache-arm64-new
-            echo "Flipping arm64 cache..."
-            rm -rf /tmp/.buildx-cache-arm64
-            mv /tmp/.buildx-cache-arm64-new /tmp/.buildx-cache-arm64
-          fi
